version: "3.7"
services:
  postgres:
    image: "postgres:10"
    container_name: "postgres-ma"
    environment:
      - POSTGRES_USER=xaeydrcv
      - POSTGRES_PASSWORD=DgYn34WETAm8GMiAIZSYfJu9KBqh-gx2
      - POSTGRES_DB=xaeydrcv
    ports:
      - "5433:5432"
    volumes:
      - postgres_faka_data:/var/lib/postgresql/data:z  
volumes:
    postgres_faka_data:

# run container
# docker-compose -p ma up -d